id: sample
pretrained: null
seed: 2612
amp: true
model_ema: 
    model_ema_steps: 2
    model_ema_decay: 0.99952 # 1 - 24/datasize
model:
    name: BaseClassifier
    args:
        extractor_cfg: 
            name: ResNetExtractor
            args:
                version: resnet50
        nclasses: 10
optimizer:
    name: AdamW
    args:
        lr: 4.0e-3
loss:
    name: CrossEntropyLoss
    args:
        label_smoothing: 0.1
metric:
    - name: Accuracy
      args:
    - name: F1
      args:
        nclasses: 10
scheduler: 
    name: WarmupLinearCosineAnnealing
    args:
        lr_warmup_epochs: 5
dataset: 
    train:
        name: CIFAR10Dataset
        args:
            datapath: ['data/cifar-10-batches-py/data_batch_1', 'data/cifar-10-batches-py/data_batch_2', 'data/cifar-10-batches-py/data_batch_3','data/cifar-10-batches-py/data_batch_4','data/cifar-10-batches-py/data_batch_5']
            metapath: 'data/cifar-10-batches-py/batches.meta'
        loader:
            name: DataLoader
            args:
                batch_size: 256
                shuffle: True
                pin_memory: True
    val:
        name: CIFAR10Dataset
        args:
            datapath: ['data/cifar-10-batches-py/test_batch']
            metapath: 'data/cifar-10-batches-py/batches.meta'
        loader:
            name: DataLoader
            args:
                batch_size: 256
                pin_memory: True

trainer: 
    nepochs: 600
    val_step: 1
    log_step: 1
    log_dir: runs
