id: sample
pretrained: null
seed: 2612
model_ema: 
    model_ema_steps: 32
    model_ema_decay: 0.99998
model:
    name: BaseClassifier
    args:
        extractor_cfg: 
            name: ResNetExtractor
            args:
                version: resnet50
        nclasses: 10
optimizer:
    name: Adam
    args:
        lr: 1.0e-3
loss:
    name: CrossEntropyLoss
    args:
        label_smoothing: 0.1
metric:
    - name: Accuracy
      args:
    - name: F1
      args:
        nclasses: 10
scheduler: 
    name: WarmupLinearCosineAnnealing
    args:
        lr_warmup_epochs: 50
dataset: 
    train:
        name: CIFAR10Dataset
        args:
            datapath: ['/media/aioz-thang/data3/aioz-thang/jvn/torchism/data/CIFAR10/cifar-10-batches-py/data_batch_1', '/media/aioz-thang/data3/aioz-thang/jvn/torchism/data/CIFAR10/cifar-10-batches-py/data_batch_2', '/media/aioz-thang/data3/aioz-thang/jvn/torchism/data/CIFAR10/cifar-10-batches-py/data_batch_3','/media/aioz-thang/data3/aioz-thang/jvn/torchism/data/CIFAR10/cifar-10-batches-py/data_batch_4','/media/aioz-thang/data3/aioz-thang/jvn/torchism/data/CIFAR10/cifar-10-batches-py/data_batch_5']
            metapath: '/media/aioz-thang/data3/aioz-thang/jvn/torchism/data/CIFAR10/cifar-10-batches-py/batches.meta'
        loader:
            name: DataLoader
            args:
                batch_size: 64
                shuffle: True
                pin_memory: True
    val:
        name: CIFAR10Dataset
        args:
            datapath: ['/media/aioz-thang/data3/aioz-thang/jvn/torchism/data/CIFAR10/cifar-10-batches-py/test_batch']
            metapath: '/media/aioz-thang/data3/aioz-thang/jvn/torchism/data/CIFAR10/cifar-10-batches-py/batches.meta'
        loader:
            name: DataLoader
            args:
                batch_size: 64
                pin_memory: True

trainer: 
    nepochs: 6000
    val_step: 1
    log_step: 1
    log_dir: runs
